## ANN Model on Classification Problem

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv('C:\\Users\\LOKESH\\Desktop\\python assignment\\Jupyter notebooks for this course\\Refactored_Py_DS_ML_Bootcamp-master\\13-Logistic-Regression\\advertising.csv')
data.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [5]:
## after EDA, these are the columns that will help by taking into the data

advertising_data = data[['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage',  'Male', 'Clicked on Ad']]
advertising_data.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
0                     68.95   35     61833.90                256.09     0   
1                     80.23   31     68441.85                193.77     1   
2                     69.47   26     59785.94                236.50     0   
3                     74.15   29     54806.18                245.89     1   
4                     68.37   35     73889.99                225.58     0   

   Clicked on Ad  
0              0  
1              0  
2              0  
3              0  
4              0

In [6]:
## split the data into X1 and Y1
X1 = advertising_data.iloc[:, 0:-1].values
y1 = advertising_data.iloc[:, 5].values
print('X1: ','\n',X1,'\n')
print('y1: ','\n',y1)

X1:  
 [[6.895000e+01 3.500000e+01 6.183390e+04 2.560900e+02 0.000000e+00]
 [8.023000e+01 3.100000e+01 6.844185e+04 1.937700e+02 1.000000e+00]
 [6.947000e+01 2.600000e+01 5.978594e+04 2.365000e+02 0.000000e+00]
 ...
 [5.163000e+01 5.100000e+01 4.241572e+04 1.203700e+02 1.000000e+00]
 [5.555000e+01 1.900000e+01 4.192079e+04 1.879500e+02 0.000000e+00]
 [4.501000e+01 2.600000e+01 2.987580e+04 1.783500e+02 0.000000e+00]] 

y1:  
 [0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 1
 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1
 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1
 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0
 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1 0 0
 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 1 0 0 1 0
 1 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 1 

In [33]:
# split the data into train, test sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X1, y1, test_size = 0.2, random_state = 0)

In [34]:
# for deeplearnig models scaling is mandatory

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
print(X_train,'\n')
print(X_test)

[[ 0.53448142 -0.92842669  0.91865168  0.84125985  1.06458129]
 [-0.82619679  1.11581557  0.60803575 -1.2505932  -0.93933644]
 [-0.52911642  1.45652261  0.928236   -1.01277338  1.06458129]
 ...
 [ 0.57647379 -1.15556472  0.03912084  1.2969858   1.06458129]
 [ 0.87104715 -0.58771965  0.39953429  1.27707211  1.06458129]
 [-1.42161102 -0.24701261 -0.86108765 -1.09723489 -0.93933644]] 

[[-3.39824839e-02 -1.04199571e+00  8.37252580e-01  1.10196897e+00
   1.06458129e+00]
 [ 1.15496573e+00  7.75108523e-01 -4.66314096e-02  1.48582252e+00
   1.06458129e+00]
 [ 9.80728718e-01 -5.87719649e-01  8.42321762e-01  8.06925906e-01
  -9.39336437e-01]
 [-1.25426828e+00 -1.33443592e-01  3.21609750e-02 -1.18856320e+00
   1.06458129e+00]
 [ 1.53352383e+00 -3.60581621e-01 -7.99170841e-01  7.10561956e-01
  -9.39336437e-01]
 [-1.22669120e+00  1.34295359e+00 -1.51373468e+00 -1.08533246e+00
   1.06458129e+00]
 [-8.01753468e-01  1.79722965e+00  2.52507293e-01 -1.15033807e+00
  -9.39336437e-01]
 [-1.12641091e+00 -

In [36]:
# importing Keras modules
import keras
from keras.models import Sequential  # for model initialisation
from keras.layers import Dense       # for adding layers to the model

In [37]:
# initialising ANN
classifier = Sequential()

In [38]:
# adding the input and first hidden layer
# for adding hidden layers --> avg(input variables + output variable)
# in our case here (5+1)/2 = 3

classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'relu', input_dim = 5))

In [39]:
# adding second hidden layer
# for second hidden layer we don't need to add input_dim

classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'relu'))

In [40]:
# adding the output layer
# at output we only have 1 node

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [41]:
# compiling the ANN

classifier.compile( optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [42]:
## fitting the ANN to training data

classifier.fit(X_train, Y_train, batch_size= 10, epochs = 50)

Epoch 1/50
800/800 [==============================] - 1s 1ms/step - loss: 0.6915 - accuracy: 0.4963
Epoch 2/50
800/800 [==============================] - 0s 219us/step - loss: 0.6594 - accuracy: 0.9237
Epoch 3/50
800/800 [==============================] - 0s 216us/step - loss: 0.5627 - accuracy: 0.9212
Epoch 4/50
800/800 [==============================] - 0s 216us/step - loss: 0.4643 - accuracy: 0.9237
Epoch 5/50
800/800 [==============================] - 0s 205us/step - loss: 0.4126 - accuracy: 0.9275
Epoch 6/50
800/800 [==============================] - 0s 221us/step - loss: 0.3830 - accuracy: 0.9287
Epoch 7/50
800/800 [==============================] - 0s 214us/step - loss: 0.3604 - accuracy: 0.9400
Epoch 8/50
800/800 [==============================] - 0s 218us/step - loss: 0.3417 - accuracy: 0.9450
Epoch 9/50
800/800 [==============================] - 0s 221us/step - loss: 0.3240 - accuracy: 0.9513
Epoch 10/50
800/800 [==============================] - 0s 214us/step - loss: 0.3089 

In [43]:
# making the predictions

y_pred = classifier.predict(X_test)

In [47]:
print(y_pred)

[[0.01399961]
 [0.00663659]
 [0.0052414 ]
 [0.9198017 ]
 [0.03780785]
 [0.9198017 ]
 [0.9198017 ]
 [0.9198017 ]
 [0.00576849]
 [0.9198017 ]
 [0.00328151]
 [0.11774314]
 [0.9198017 ]
 [0.00287212]
 [0.02165982]
 [0.04469572]
 [0.9198017 ]
 [0.00841628]
 [0.9198017 ]
 [0.00249743]
 [0.01660896]
 [0.01741639]
 [0.00311091]
 [0.06502692]
 [0.9198017 ]
 [0.01842123]
 [0.9198017 ]
 [0.06223647]
 [0.00839876]
 [0.00786719]
 [0.00347366]
 [0.9198017 ]
 [0.00933287]
 [0.9198017 ]
 [0.8693667 ]
 [0.0026995 ]
 [0.0116095 ]
 [0.01332493]
 [0.00302124]
 [0.00710499]
 [0.00790962]
 [0.9198017 ]
 [0.9198017 ]
 [0.05824201]
 [0.9198017 ]
 [0.05447176]
 [0.02458461]
 [0.9198017 ]
 [0.18331072]
 [0.9198017 ]
 [0.00549224]
 [0.00262424]
 [0.8921641 ]
 [0.766292  ]
 [0.24209435]
 [0.9198017 ]
 [0.00779384]
 [0.9198017 ]
 [0.9198017 ]
 [0.9198017 ]
 [0.00372204]
 [0.58040684]
 [0.9198017 ]
 [0.9198017 ]
 [0.9198017 ]
 [0.9198017 ]
 [0.00896123]
 [0.9198017 ]
 [0.00394506]
 [0.9198017 ]
 [0.761212  ]
 [0.01

In [48]:
# we are getting probabilities, so we have to take cut-off value
y_pred_updated = [  1 if i>0.5 else 0  for i in y_pred]
print(y_pred_updated)

[0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0]


In [49]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, y_pred_updated)
cm

array([[106,   2],
       [  3,  89]], dtype=int64)